### ISSUE TITLE
ページリンククリック時に表示するまでローディングアニメーションの表示

### ISSUE THREAD

**Issue by UNILORN** [ChiakiUehira/larave-attendance-management-system#118]
TOP画面から別ページにリンクする際、
ローディングが無いため、レスポンスが遅い場合に見づらい。
間違えて何度もクリックしてしまう懸念

**Comment by ChiakiUehira** [comment]
SPAなので大袈裟なローディングを入れると鬱陶しい
transitionの内容を考えて工夫する
