### ISSUE TITLE
提出必要書類一覧

### ISSUE THREAD

**Issue by potomoppu** [ChiakiUehira/larave-attendance-management-system#162]
- [x] 要件定義書(@UNILORN )

- [x] ガントチャート( @UNILORN )
- [x] データベース仕様書 (@ninja250 )

- [x] E-R図 (@ninja250 )

- [x] 画面遷移図 ( @UNILORN )
- [x] プレゼン資料作成 ( @UNILORN )
- [x] テスト仕様書 (@potomoppu )  

- [ ] 画面設計図 (@2B28KN )  

- [ ] システム説明書( @ninja250 )

**Comment by UNILORN** [comment]
ここにアサインした人書きます！

**Comment by UNILORN** [comment]
？？？　これクローズしたのはなんでかな？？

**Comment by potomoppu** [comment]
#169 のほうに移行したのかと

**Comment by UNILORN** [comment]
ああごめんごめん。　Excelファイルにして、印刷できる状態になったものが #169 になってて、
GoogleDriveとかに個々で保存されてるものは対象外にしてるねん。（GoogleDriveから移行した時に印刷時調整が必要なため）
印刷ボタン一個で調整なしのファイルを作った時点で #169 に反映するかんじなので、基本ここのissueで確認お願いします！！　最終調整は @UNILORN がやります。

**Comment by potomoppu** [comment]
申し訳！

**Comment by UNILORN** [comment]
Thank you!!

**Comment by potomoppu** [comment]
No problem.

**Comment by UNILORN** [comment]
@potomoppu テスト仕様書Fixですか？

**Comment by potomoppu** [comment]
@UNILORN  yeah completed.
