### ISSUE TITLE
ユーザ招待修正

### ISSUE THREAD

**Issue by ChiakiUehira** [ChiakiUehira/larave-attendance-management-system#47]
path /management/invite

以下は必須項目

苗字
名前
Eメール
性別
マネージャフラグ -> タイプ
グループ

以下の項目は必要がないもので削除してよい

パスワード 
理由 管理者が決めなくていい

**Comment by yuyutyanu** [comment]
決めなくてもいいけど、管理者が登録できないっていう制限をあえて設ける必要はないとおもったから項目として残してる
